<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find robot_description)/urdf/common_inertial.xacro"/>
    
    <xacro:macro name="base_xacro" params="prefix:='' length radius">
        <link name="${prefix}base_footprint" />
            
        <link name="${prefix}base_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="${prefix}white">
                    <color rgba="1.0 1.0 1.0 0.8"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
        </link>
        
        <joint name="${prefix}base_joint" type="fixed">
            <origin xyz="0.0 0.0 ${length/2 + 0.032 - 0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}base_footprint"/>
            <child link="${prefix}base_link"/>
        </joint>
        
        <gazebo reference="${prefix}base_link">
            <material>Gazebo/White</material>
        </gazebo>
    </xacro:macro>
</robot>
